#cloudbuild.yaml
steps:
- name: 'docker/compose:1.27.0'
  args: ['-f', 'docker-compose-test.yml', 'up', '-d']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'eu.gcr.io/primeval-falcon-295315/parking_project', 'eu.gcr.io/primeval-falcon-295315/parking_project' ]
images: [ 'eu.gcr.io/primeval-falcon-295315/parking_project' ]